### ISSUE TITLE
Moving assets out of the /static directory, possible? :)

### ISSUE THREAD

**Issue by fgimian** [miracle2k/flask-assets#35]
Hello there, I think that webassets and the related Flask module are awesome and just had a few questions about the way files are read and structured within a Flask project.

Suppose we wish to keep track of 3 item types:
1. Non-compiled assets (e.g. LESS CSS, Stylus, Coffeescript .etc)
2. Compiled assets (e.g. CSS, JS)
3. Third party libraries used in a project (e.g. jQuery, Twitter Bootstrap)

I think a suitable directory structure would probably look something like this:

```
flask_project/assets/less/...   <- (1) Non-compiled assets
flask_project/assets/coffee/... <- (1) Non-compiled assets
flask_project/static/js/...     <- (2) Compiled assets
flask_project/static/js/...     <- (3) 3rd Party Libraries
flask_project/static/css/...    <- (2) Compiled assets
flask_project/static/css/...    <- (3) 3rd Party Libraries
```

I have been experimenting with Flask-Assets and can't seem to find a way to achieve this without doing something like this in the template:

``` html
{% assets filters="less", output="css/style.css",
          "../assets/less/style.less", "../assets/less/import.less" %}
    <link rel="stylesheet" type="text/css" media="screen" href="{{ ASSET_URL }}" />
{% endassets %}
```

I also attempted to use the ASSETS_LOAD_PATH config item but didn't have any luck.

Is there any way to specify the source directory independently from the destination directory?

Also another little question, is the cache really needed?  For example, I pictured that it would work as follows.
1. I update my non-compiled source
2. The hash is saved in a dict (or similar)
3. An output file is generated
4. Next time I refresh the page, the hash is calculated against each file and compared to the value in the dict
5. If it has changed, repeat steps above

Please let me know your thoughts and if I'm missing something :)

Thank you so much and keep up the great work!
Fotis

**Comment by JavaWantaBe** [comment]
Missing something here. 
Project consists of flask static directory but with compiled assets they are in the parent directory:

Bundles initialized like:
`bundles = {
        'compressed_css': Bundle('css/libs/bootstrap.css',
                             'css/libs/font-awesome.css',
                             'css/animate.css',
                             'css/style.css',
                             filters='cssmin',
                             output='../../output/static/layout_css.css')
        }
....
`
File structure:

application - \ \n
---->static - \
-------->unminified.css
---->init.py
output - \
---->static - \
-------->compressed.css

In the templates:
`{% assets 'compressed_css' %}
        <link href="{{ ASSET_URL }}" rel="stylesheet">
 {% endassets %}`

Static directory *is not being changed* in flask but using the WSGI ProxyFix which resolves the 'static' to 'output/static'. SO, the question is, how to change the resolver for assets so that in the template it resolves the url to /static/compressed.css instead of /output/static/compress.css?

**Comment by JavaWantaBe** [comment]
Figured it out, sorry. When specifying `output` in your bundle, leaving it with just a name instead of a directory reference solves some of it.

Then adding:
`
assets.directory = os.path.join(app.config.get('PROJECT_PATH'), 'output/static')
`
Did the rest.

**Comment by phdesign** [comment]
I found this thread by searching for the same error message @cburmeister received. Thanks to your advice @miracle2k this is what I got working:

`assets.py`
```
from flask_assets import Bundle, Environment

bundles = {...}

assets = Environment()
assets.register(bundles)


def init_assets(app):
    with app.app_context():
        assets.append_path("assets")
```

`__init__.py`
```
from .assets import assets, init_assets

def create_app():
    assets.init_app(app)
    init_assets(app)
```

---

## Suggested change

I don't need to do this for any other flask extension. I would have expected this to work

```
def create_app():
    assets.init_app(app)
    assets.append_path("assets")
```

but I think this fails because we never set `Enviroment.app` when calling `init_app`, however it is set if you pass app to the `Environment` constructor.

[flask_assets.py@304](https://github.com/miracle2k/flask-assets/blob/master/src/flask_assets.py#L304)
```
    def __init__(self, app=None):
        self.app = app
```

Can I suggest that you also set the `app` property in `init_app` like this:

```
    def init_app(self, app):
        self.app = app
        app.jinja_env.add_extension('webassets.ext.jinja2.AssetsExtension')
        app.jinja_env.assets_environment = self
```

Then we won't need to push an app context.
