### ISSUE TITLE
Bower support?

### ISSUE THREAD

**Issue by lnielsen** [miracle2k/flask-assets#93]
Hi,

Would you be interested in having support for bower integrated into Flask-Assets or Webassets? What we have in mind is being able to specify bower dependencies in Bundles, e.g.:

```python
css = Bundle(
    'less/styles.less',
    filters='less, cleancss',
    output='gen/styles.%(version)s.css',
    bower={
        "bootstrap": "~3.3.5",
    }
)
```

Then have a CLI command similar to below to collect bower requirements from all bundles in an environment in order to generate a ``bower.json``:

```console
$ manage.py bower
{
  "name": "",
  "dependencies": {
    "bootstrap": "~3.3.5",
  }
}
```

A typical use would be like below (generate ``bower.json``, run bower install, then build assets):

```console
$ manage.py bower --output-file bower.json
$ bower install
$ manage.py assets build
```

The difference from just writing a ``bower.json`` in your text editor is that it allows an application to integrate external bundles without having to worry about which assets you need to download (e.g. collecting bower requirements from all applications in ``INSTALLED_APPS`` in a Django). 

If it has any interest, we'll be happy to create a PR, otherwise just close the issue.

Cheers,
Lars

**Comment by miracle2k** [comment]
I've done something similar myself recently with NPM packages, except just external to webassets. I subclasses the command line interface to add a "assets init" command. The dependencies themselves were defined outside of the bundles.

I don't think this is something that belongs in the core, since it can easily be added separately, and is somewhat specific to peoples requirements and workflow.
